---
title: "Assignment 2"
output: pdf_document
---

install.packages("ISLR")
require(ISLR)
data(USArrests)
data(NCI60)
str(USArrests)

states = row.names(USArrests)
states

names(USArrests)

apply(USArrests, 2, mean)

pr.out=prcomp(USArrests, scale=TRUE)

biplot(pr.out, scale=0)
pr.out$rotation=-pr.out$rotation
pr.out$x=-pr.out$x
biplot(pr.out, scale=0, cex = 0.5)

pr.var=pr.out$sdev^2
pr.var
pve=pr.var/sum(pr.var)
pve
plot(pve, xlab="Principal Component", ylab="Proportion of Variance Explained", ylim=c(0,1), type='b')
plot(cumsum(pve), xlab="Principal Component", ylab="Proportion of Variance Explained", ylim=c(0,1), type='b')

set.seed(2)
x=matrix(rnorm(50*2), ncol=2)
x[1:25,1]=x[1:25,1]+3
x[1:25,2]=x[1:25,2]-4
km.out=kmeans(x,2,nstart=20)
km.out$cluster
plot(x, col=(km.out$cluster+1), pch=20)


set.seed(4)
km.out=kmeans(x,3,nstart=20)
km.out
plot(x, col=(km.out$cluster+1), pch=20, cex=2)

hc.complete=hclust(dist(x), method="complete")
hc.single=hclust(dist(x), method="single")
hc.average=hclust(dist(x), method="average")
par(mfrow=c(1,3))
plot(hc.complete, cex=.9)
plot(hc.average, cex=.9)
plot(hc.single, cex=.9)
cutree(hc.complete, 2)

